version: '3.9'

services:
  mongodb:
    image: mongo:8
    container_name: mongo-ecommerce-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ecommerce_multitienda
    ports:
      - "27017:27017"
    volumes:
      - mongo-ecommerce-mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mongo-ecommerce-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-ecommerce-mongo-express
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    networks:
      - mongo-ecommerce-net

  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: mongo-ecommerce-quarkus-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://admin:admin123@mongodb:27017/ecommerce_multitienda?authSource=admin&retryWrites=false
      QUARKUS_MONGODB_DATABASE: ecommerce_multitienda
      QUARKUS_REST_CLIENT_POSTGRESQL_API_URL: http://host.docker.internal:8082
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_HTTP_CORS_ENABLED: "true"
      QUARKUS_HTTP_CORS_ORIGINS: http://localhost:5173
      QUARKUS_HTTP_CORS_METHODS: GET,POST,PUT,DELETE,PATCH,OPTIONS
      QUARKUS_HTTP_CORS_HEADERS: accept,authorization,content-type,x-invitado,x-session-id
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mongo-ecommerce-net

networks:
  mongo-ecommerce-net:
    driver: bridge

volumes:
  mongo-ecommerce-mongo-data: