# MongoDB connection
quarkus.mongodb.connection-string=mongodb://admin:admin123@mongodb:27017/?authSource=admin
quarkus.mongodb.database=ecommerce_multitienda
quarkus.mongodb.min-pool-size=5
quarkus.mongodb.max-pool-size=20

# HTTP
quarkus.http.port=8080

# Jackson
quarkus.jackson.property-naming-strategy=SNAKE_CASE
quarkus.jackson.fail-on-unknown-properties=false

# JWT (validación de tokens desde PostgreSQL)
# mp.jwt.verify.publickey.location=classpath:publicKey.pem
# mp.jwt.verify.issuer=https://bo.com.proj
# smallrye.jwt.sign.key.location=classpath:privateKey.pem

# Docker profile (if needed)
%prod.quarkus.mongodb.connection-string=mongodb://admin:admin123@mongodb:27017/ecommerce_multitienda?authSource=admin

# Logging
quarkus.log.level=INFO
quarkus.log.category."bo.com.proj".level=DEBUG

# Security configuration
quarkus.http.auth.permission.public.paths=/hello,/q/*
quarkus.http.auth.permission.public.policy=permit

# Swagger UI (activado para todos los perfiles
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.enable=true
quarkus.smallrye-openapi.enable=true

# Perfil desarrollo
%dev.quarkus.mongodb.connection-string=mongodb://localhost:27017/ecommerce_multitienda
%dev.quarkus.http.port=8081
%dev.quarkus.log.level=DEBUG